### ISSUE TITLE
Allow for a `tuple_file` option in the store file format

### ISSUE THREAD

**Issue by rhamzeh** [openfga/cli#179]
Currently, we support a `model_file` option in addition to `model` for users who prefer to edit their model in a separate file.

We should support a `tuple_file` that does the same for tuples.

That file will be the same format as accepted by `write`

```
name: Some Store
model_file: ./model.fga
tuple_file: ./tuples.yaml
tests:
  - name: test 1
    tuple_file: ./test1_tuples.json
    check: ...
    list_objects: ...
  - name: test 2
    tuple_file: ./test2_tuples.json
    check: ...
    list_objects: ...
```
