### ISSUE TITLE
Support exporting store data into the store file format

### ISSUE THREAD

**Issue by rhamzeh** [openfga/cli#180]
Add a new `export` command under store: `fga store export`

e.g.
```shell
fga store export --output-file store.fga.yaml
```

This method should:
1. Get the store specified in order to get the name. If this fails for any reason, use the Store ID for the name (Store ID is required)
2. Get the model specified, if not specified get the latest model (Model ID is optional)
3. Read the tuples (all the tuples)
4. Read the assertions for the model specified or latest
5. display that data in the store file file format

This method in essence wraps:
* `store get`
* `model get`
* `tuple read`
* And maps assertions to check test

The data should be displayed in the following format:
```yaml
name: Store Name
model: |
  The model
tuples:
  - user: ...
    relation: ...
    object: ...
tests:
  - name: test 1
    checks:
      - user: ...
        object: ...
        assertions:
          relation1: true
          relation2: false
```
