### ISSUE TITLE
Support multiple tuple files in tests

### ISSUE THREAD

**Issue by xtsee** [openfga/cli#233]
**Scope**
Allowing multiple tuple files gives you the option to break up your fixtures data (tuples) and reuse them across different tests. For example, you might have a set of tuples that contain all companies and another set of tuples for teams. This should make managing the test data a lot easier.

**Example**

```yaml
tests: # required
  - name: test-1
    # tuple_file: ./tuples.yaml # tuples that would apply per test
    # tuple_file: # or multiple
    #   - ./tuples-1.yaml
    #   - ./tuples-2.yaml
```
