### ISSUE TITLE
Support `list_users` in the Store File

### ISSUE THREAD

**Issue by rhamzeh** [openfga/cli#304]
Add support for list_users in the store file

For the store file, we have a choice to make in how we represent the expected output. It can be:

1- Go for consistency with other fields:
```
    -  list_users:
        - object: document:1
          user_filter:
            - type: user
            - type: team
              relation: member
          context: {}
          assertions:
            can_view:
              users:
                - user:ewan
                - team:fga#member
                - employee:*
              excluded_users:
                - user:ewan
                - team:fga#member
```

2- Stick with API Design
```
    -  list_users:
        - object: document:1
          user_filter:
            - type: user
            - type: team
              relation: member
          context: {}
          assertions:
            can_view:
              users:
                  - object:
                      type: user
                      id: ewan
                  - userset:
                      type: team
                      id: fga
                      relation: member
                  - wildcard:
                      type: employee
                      wildcard: {}
                excluded_users:
                  - object:
                      type: user
                      id: ewan
                  - userset:
                      type: team
                      id: fga
                      relation: member
```

3- A simplified form of the API design
```
    -  list_users:
        - object: document:1
          user_filter:
            - type: user
            - type: team
              relation: member
          context: {}
          assertions:
            can_view:
              users:
                - type: user
                  id: ewan
                - type: team
                  id: fga
                  relation: member
                - type: employee
                  wildcard: {}
              excluded_users:
                - type: user
                  id: ewan
                - type: team
                  id: fga
                  relation: member
```

We're going to go with option (1)
