### ISSUE TITLE
Support for contextual tuples in model tests

### ISSUE THREAD

**Issue by mbarralo** [openfga/cli#327]
Currently the contextual tuples don't seem to be supported in the model tests, although it is possible using API requests with curl, Postman, etc.

Example:
```
  - name: User can see account from specific branch
    check:
    - user: user:anne
      object: account:1
      contextual_tuples:
        - user: user:anne
          relation: assignee
          object: branch:lisbon
      assertions:
        can_view: true
```

**Comment by PatrickMunsey** [comment]
It appears this is already supported with the `tuple_file:` field at the global test and per test level. See the example for [fga model test](https://github.com/openfga/cli?tab=readme-ov-file#parameters-11)

```yaml
name: Store Name # store name, optional
# model_file: ./model.fga # a global model that would apply to all tests, optional
# model can be used instead of model_file, optional
model: |
  model
    schema 1.1
  type user
  type folder
    relations
      define owner: [user] 
      define parent: [folder]
      define can_view: owner or can_view from parent
      define can_write: owner or can_write from parent
      define can_share: owner
# tuple_file: ./tuples.yaml # global tuples that would apply to all tests, optional
tuples: # global tuples that would apply to all tests, optional
  - user: folder:1
    relation: parent
    object: folder:2
tests: # required
  - name: test-1
    description: testing that the model works # optional
    # tuple_file: ./tuples.json # tuples that would apply per test
    tuples:
      - user: user:anne
        relation: owner
        object: folder:1
    check: # a set of checks to run
      - user: user:anne
        object: folder:1
        assertions:
          # a set of expected results for each relation
          can_view: true
          can_write: true
          can_share: false
```

**Comment by ewanharris** [comment]
Thanks for the issue @mbarralo. @PatrickMunsey is correct that this is achievable using the `tuples` or `tuple_file` per test, these tuples will then be used as part of the assertions ran during that test.

Please let us know if you have any further questions about the usage.

**Comment by mbarralo** [comment]
Thank you for the reply. For me it seemed more intuitive to think about contextual tuples as something that would be part of the check itself and not part of the tuples that model all checks of the test (hence my example). The distinction of persisted tuples (tuples) and runtime (contextual) tuples could be of value.

**Comment by aaguiarz** [comment]
For what is worth, is currently at the test level too, just not at each check level, so you can reuse the same contextual tuples for more than one check:

```
tests: # required
  - name: test-1
    description: testing that the model works # optional
    # tuple_file: ./tuples.json # tuples that would apply per test
    tuples:
      - user: user:anne
        relation: owner
        object: folder:1
    check: # a set of checks to run
      - user: user:anne
        object: folder:1
        assertions:
          # a set of expected results for each relation
          can_view: true
          can_write: true
          can_share: false
```

If I understand correctly, if you write one test per check, then you can achieve what you want.
