### ISSUE TITLE
Unable to specify store-id when importing a store from file or creating new

### ISSUE THREAD

**Issue by PatrickMunsey** [openfga/cli#331]
I'm unable to create a store either from a file or scratch while specifying the store-id. 

I'd like to be able to specify the store id during creation so that the entire configuration and secret management for setting up openfga can be set prior to deployment.

I've seen that store-id can be specified for the openfga CLI [fga store import](https://github.com/openfga/cli?tab=readme-ov-file#import-store) command, however specifying the store id with `--store-id`  leads to the store not being created at all.

e.g. 
`fga store import --file test-store.yaml --store-id 01HYHGP755KA1BQMBR568RVKKV`

```yaml
# test-store.yaml
name: test-store
model: |+
  model
    schema 1.1

  type user

  type group
    relations
      define member: [user]

  type folder
    relations
      define can_create_file: owner
      define owner: [user]
      define parent: [folder]
      define viewer: [user, user:*, group#member] or owner or viewer from parent

  type doc
    relations
      define can_change_owner: owner
      define can_read: viewer or owner or viewer from parent
      define can_share: owner or owner from parent
      define can_write: owner or owner from parent
      define owner: [user]
      define parent: [folder]
      define viewer: [user, user:*, group#member]

tuples: []
tests:
  - name: Tests
    check: []

```
`fga store list`
```sh
{
  "continuation_token":"",
  "stores": []
}
```

It would also be nice to se a `--store-id` parameter added to the [fga store create](https://github.com/openfga/cli?tab=readme-ov-file#create-store) command.

e.g. `fga store create --name test-store --model test-model.fga --store-id 01HYHGP755KA1BQMBR568RVKKV`
