### ISSUE TITLE
Cli Fails "panic makechan: size out of range"

### ISSUE THREAD

**Issue by sashokbg** [openfga/cli#333]
Hello, I have copied the following example and tried running it locally but I get an error message:

Example:
```
https://github.com/openfga/sample-stores/blob/main/stores/banking/store.fga.yaml
```

My env:
```
Linux alexander-p14s 6.8.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 17 Apr 2024 15:20:28 +0000 x86_64 GNU/Linux
```

fga version:
```
fga version v`0.4.0` (commit: `7f8f86973799d9be6ae443147977e36595461bc9`, date: `2024-05-07T13:11:24Z`)
```

docker compose:
```
version: '3.8'

networks:
  openfga:

services:
  postgres:
    image: postgres:14
    container_name: postgres
    networks:
      - openfga
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    depends_on:
      postgres:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: migrate
    command: migrate
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
    networks:
      - openfga

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    healthcheck:
      test: [ "CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081" ]
      interval: 5s
      timeout: 30s
      retries: 3
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - OPENFGA_LOG_FORMAT=json
    command: run
    networks:
      - openfga
    ports:
      # Needed for the http server
      - "8080:8080"
      # Needed for the grpc server (if used)
      - "8081:8081"
      # Needed for the playground (Do not enable in prod!)
      - "3000:3000"

  init_store:
    depends_on:
      openfga:
        condition: service_healthy
    image: nginx
    command:
      - sh
      - -c
      - "curl -X POST http://openfga:8080/stores -d '{\"name\": \"bankerise-corporate\"}'"
    networks:
      - openfga


```

Error:

> 
> panic: makechan: size out of range
> 
> goroutine 1 [running]:
> github.com/openfga/openfga/pkg/storage/storagewrappers.NewBoundedConcurrencyTupleReader(...)
> 	/home/runner/go/pkg/mod/github.com/openfga/openfga@v1.5.4-rc1/pkg/storage/storagewrappers/boundedconcurrency.go:45
> github.com/openfga/openfga/pkg/server.(*Server).Check(0x99b0278, {0x8cac2e8, 0x93ea1a0}, 0x9e1f9b0)
> 	/home/runner/go/pkg/mod/github.com/openfga/openfga@v1.5.4-rc1/pkg/server/server.go:792 +0xa5e
> github.com/openfga/cli/internal/storetest.RunSingleLocalCheckTest(...)
> 	/home/runner/work/cli/cli/internal/storetest/localtest.go:18
> github.com/openfga/cli/internal/storetest.RunLocalCheckTest(0x99b0278, {{0x9c078a4, 0x9}, {0x9c97ce0, 0x1d}, 0x9f86028, 0x99b7980}, {0x9adaf08, 0xd, 0xd}, ...)
> 	/home/runner/work/cli/cli/internal/storetest/localtest.go:53 +0x2b9
> github.com/openfga/cli/internal/storetest.RunLocalTest(0x99b0278, {{0x995ea20, 0x18}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, ...}, ...)
> 	/home/runner/work/cli/cli/internal/storetest/localtest.go:242 +0x1b2
> github.com/openfga/cli/internal/storetest.RunTest(0x9a18218, 0x99b0278, {{0x995ea20, 0x18}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...}, ...)
> 	/home/runner/work/cli/cli/internal/storetest/tests.go:29 +0x1f4
> github.com/openfga/cli/internal/storetest.RunTests(0x9a18218, 0x9c16640, {0x8b4247f, 0x7})
> 	/home/runner/work/cli/cli/internal/storetest/tests.go:47 +0x22e
> github.com/openfga/cli/cmd/model.init.func3(0x93b3260, {0x98fc300, 0x0, 0x6})
> 	/home/runner/work/cli/cli/cmd/model/test.go:60 +0x254
> github.com/spf13/cobra.(*Command).execute(0x93b3260, {0x98fc2d0, 0x6, 0x6})
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaa0
> github.com/spf13/cobra.(*Command).ExecuteC(0x93b2960)
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x458
> github.com/spf13/cobra.(*Command).Execute(...)
> 	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
> github.com/openfga/cli/cmd.Execute()
> 	/home/runner/work/cli/cli/cmd/root.go:48 +0x23
> main.main()
> 	/home/runner/work/cli/cli/cmd/fga/main.go:21 +0x17
