### ISSUE TITLE
The CLI does not display the proper message with a list_users test fails

### ISSUE THREAD

**Issue by aaguiarz** [openfga/cli#388]
For example, if the store.fga.yaml file has:

```
model: |
   model
     schema 1.1
   type user
   type organization
      relations
        define member : [user]
tuples:
    - user: user:anne
      relation: member
      object: organization:acme

tests:
    - name: Test for basic example
      list_users:
        - object: organization:acme
          user_filter:
            - type: user
          assertions:
            member:
              users: []
```

When running`fga model test --tests store.fga.yaml` you get:

```
ⅹ ListUsers(object={Type:organization Id:acme},relation=member,user_filter={Type:user Relation:<nil>}): expected={Users:[]}, got=N/A
```

You should get something like:

```
ⅹ ListUsers(object={Type:organization Id:acme},relation=member,user_filter={Type:user Relation:<nil>}): expected={Users:[]}, got={Users:[user:anne}]
```

ⅹ ListUsers(object={Type:feature Id:issues},relation=can_access,user_filter={Type:user Relation:<nil>}): expected={Users:[user:charles user:beth]}, got=N/A
