### ISSUE TITLE
Improvement: Running multiple test files at once

### ISSUE THREAD

**Issue by Oscmage** [openfga/cli#423]
It would be lovely to run multiple test files at once similar to the github action.

Something like

```
fga model test --tests ./tests/*.fga.model
```

The [github action](https://github.com/openfga/action-openfga-test) got this feature, example:

```
      - name: Run Test
        uses: openfga/action-openfga-test@v0.1.1
        with:
          test_files_pattern: "./tests/*.fga.yaml"
```
