### ISSUE TITLE
[Feature] Support relative parent paths for module files

### ISSUE THREAD

**Issue by AdamSendible** [openfga/cli#507]
### Description

`fga.mod` file do not support relative parent paths (e.g. `../model.fga`) to module files listed in `contents`.  Files must reside in a child directory of the `fga.mod` location. 

What makes this particularly problematic is that module files must be named `fga.mod` and cannot have arbitrary names therefore preventing multiple module from being in the same directory.

### Benefits

- Enhanced composition flexibility
- Ability to avoid duplication of module definitions

### Use Case

As part of a model migration system I aim to support incremental model migrations and need to version models by date while reusing module definitions from previous versions that remain 
unchanged.

#### Example

```
models
├── 20250601
│   ├── core.fga
│   └── fga.mod
├── 20250604
│   ├── wiki.fga
|   └── fga.mod
└── 20250605
    ├── github.store.fga.yaml
    │   ├── issue-tracker/projects.fga
    |   └── issue-tracker/tickets.fga
    └── fga.mod
```

`20250605/fga.mod`
```yaml
schema: '1.2'
contents:
  - ../20250601/core.fga # Not supported
  - ../20250604/wiki.fga # Not supported
  - issue-tracker/projects.fga
  - issue-tracker/tickets.fga
```
